src/components/map/MapPage.js
:rocket: Ready
Normalizes the longitude of the map bounds to the range [-180, 180] for compatibility with the Falling Fruit API.
Fixes #28 
The general help function `normalizeLongitude` may be best moved to a new or existing module under `/utils`. I will leave that decision to you, as I don't have a good sense of how the code is meant to be organized.
=> 🤰🏿 Normalize longitude to range [-180, 180] (closes #28)

src/components/map/Cluster.js, src/redux/mapSlice.js
Just because the map feels a little empty when clusterZoom = mapZoom.
- Display {zoom + 1} clusters on {zoom} map.
- Make cluster background slightly transparent for when they overlap.
If we wanted to match fallingfruit.org exactly, it would be clusterZoom = mapZoom > 3 ? mapZoom + 1 : mapZoom. I think we did this to reduce overlaps for mapZooms 0-3. But I think it looks kinda cool with more stuff on the map.
:rocket: Ready
More clusters!
=> 😩 Increase density of displayed clusters

src/components/table/DataTable.js, src/components/table/ImportsTable.jsx
:rocket: Ready
- Adds loading skeleton to imports table so the user isn't told the dataset is empty while loading
- Misc Changes.
- Data tables without `onRowClick` callbacks no longer show a pointer and hover effect
Fixes #247
=> 🌀 Data Table Loader

src/components/about/PageTemplate.js, src/components/desktop/MainPane.js, src/components/desktop/NavBack.js, src/components/entry/EntryDrawer.js, src/components/entry/EntryNav.js, src/components/entry/EntryOverview.js, src/components/entry/EntryReviews.js, src/components/form/EditableForm.js, src/components/form/LocationForm.js, src/components/form/LocationNav.js, src/components/list/InfiniteList.js, src/components/list/PagedList.js, src/components/map/MapPage.js, src/components/settings/SettingsPage.js, src/components/table/ImportsTable.jsx, src/utils/useAppHistory.js, src/utils/useRoutedTabs.js
:rocket: Ready
* Wraps useHistory from react-router-dom to automatically preserve map state in URL when pushing new routes.
* Avoids the need for getPathWithMapState
* Always use `useAppHistory` instead of `useHistory` in case we need future functionality
Fixes #232
=> 🪝 Add useAppHistory hook

src/components/filter/Filter.js, src/components/filter/RCTreeSelectSkeleton.js, src/components/ui/GlobalStyle.js, src/components/ui/TopBar.js
:rocket: Ready
Delays filter rendering until rest of map page mounts. Prevents seconds of delay when clicking the map page from another.
=> 🎛 Filter Render Delay

src/components/auth/AccountPage.js, src/components/desktop/NavBack.js, src/components/filter/Filter.js, src/components/form/LocationForm.js, src/components/map/TrackLocationButton.js, src/redux/filterSlice.js, src/redux/selectParams.js
:rocket: Ready
Fixes:
- After clicking edit on an entry, the edit button stays around but doesn't do anything on click (not sure if this is intentional)
- After clicking settings and edit, a screen that says "Editing Location" shows up (not sure what is supposed to show up)
- Logging out on the accoutn page isn't reflected in the UI
- Can't log out of mobile. I tried clicking the logout button, but nothing would happen.
- No way to make a property private
- Seasonality dropdown is super small/difficult to use (looks like it's under a white pane)
- Edit button should not show if not logged in
- Unable to save a location after adding types. I clicked a location near me and tried adding some more types. It could not save and I got an error message. I was logged in.
- "Municipal" checkbox is …
=> 🐛 Miscellaneous bug fixes

src/utils/buildTypeSchema.js
The API currently requires that a type have at least either an English common name or a scientific name. However, a type with only the former broke the building of the type tree, resulting is an empty tree. This pull request fixes this issue.
=> 🔧 Fix handling of types without English common names

src/components/entry/EntryOverview.js, src/components/entry/Review.js
Sets CSS `white-space: pre-line` to elements displaying the following attributes:
- Location.description
- Review.comment
This ensures that line breaks (`\n`) are displayed correctly and as they appear in the form text areas.
@Qrtn @SirajChokshi Is this the best way to achieve this (setting style on elements directly), or can just the style be made into a reusable component? This situation could occur anywhere that a text field (user bio, dataset comments, ...) is displayed outside a textarea input.
=> 💖 Display line breaks in text fields from API

src/components/entry/EntryOverview.js, src/components/entry/Review.js
Since CSS `word-break: break-word` is deprecated, this uses the equivalent
- `word-break: normal` (the default)
- `overflow-wrap: anywhere`
See https://github.com/falling-fruit/falling-fruit-web/pull/336.
=> ✨ Only wrap words that would otherwise overflow

src/components/settings/SettingsPage.js, src/i18n.js, src/redux/useTypesById.js
Ensures that i18n.language is a language code with no region code (e.g. 'en', not 'en-US' or 'en-GB'), simplifying and fixing app logic.
Closes #293.
=> 👱🏿‍♀️ Drop region code from locale

src/components/entry/Review.js, src/components/entry/ReviewSummary.js, src/components/form/ReviewForm.js, src/constants/ratings.js
Review attributes `fruiting`, `quality_rating`, and `yield_rating` are now read, written, and displayed in a matter consistent with the zero-based scales used by the API.
Also fixes fruiting summary and review descriptions to use `observed_on` (misspelled `observed_at`).
Closes #331 .
=> 🔧 Fix creation and display of review fruiting and ratings

src/components/about/ProjectPage.js, src/components/about/aboutRoutes.js, src/components/auth/AccountPage.js, src/components/auth/ConfirmationPage.js, src/components/auth/ConfirmationResendPage.js, src/components/auth/LoginPage.js, src/components/auth/PasswordResetPage.js, src/components/auth/PasswordSetPage.js, src/components/auth/SignupPage.js, src/components/auth/authRoutes.js, src/components/desktop/Header.js, src/components/desktop/MainPane.js, src/components/desktop/NavBack.js, src/components/desktop/SidePaneSwitch.js, src/components/entry/EntryMobile.js, src/components/entry/EntryOverview.js, src/components/entry/EntryReviews.js, src/components/entry/ReviewButton.js, src/components/form/EditableForm.js, src/components/form/LocationForm.js, src/components/form/LocationNav.js, src/components/list/InfiniteList.js, src/components/list/PagedList.js, src/components/map/MapPage.js, src/components/mobile/MobileLayout.js, src/components/mobile/TopBarSwitch.js, src/components/settings/SettingsPage.js, src/components/table/ImportsTable.jsx, src/utils/getInitialUrl.js, src/utils/useRoutedTabs.js
The following path changes are proposed for backwards compatibility with the existing website (and all the links in the wild to said website):
- /about/project -> /about
- /about/press -> /press
- /about/share -> /sharing
- /about/data -> /data + /datasets (combines both pages)
Deprecated alternate paths /maps and /inventories are ignored.
- /about/dataset/:id -> /imports/:id
- /entry/:id -> /locations/:id
- /entry/new -> /locations/new
- /entry/edit -> /locations/edit
- /account -> /users/edit
- /login -> /users/sign_in
- /signup -> /users/sign_up
- /password -> /users/password
- /password/reset -> /users/password/new
- /password/set -> /users/password/edit (API update required)
- /confirmation/new -> /users/confirmation/new
- /confirmation -> /users/confirmation (API update required)
- …
=> 😤 Match paths of existing website

src/components/map/ConnectedGeolocation.js, src/components/map/Map.js, src/components/map/TrackLocationButton.js, src/redux/mapSlice.js
- Represent denied location with lower opacity and not clickable
- toast other errors (should be rare)
- Also enable high accuracy geolocation option
Closes #351 
Closes #380 
Closes #381 
Makes it look like this:
=> Improve geolocation

src/components/map/Cluster.js, src/components/map/Location.js, src/components/map/Map.js, src/components/map/MapPage.js
Disable click events on locations so they don't confuse. Closes #312 .
=> When adding new location, keep showing previous locations and clusters

src/components/mobile/MobileLayout.js
/locations/new has map, but /locations/new/details doesn't. Closes #394
=> don't show map behind a location details form

src/components/filter/Filter.js, src/components/filter/RCTreeSelect.js, src/redux/filterSlice.js, src/utils/buildTypeSchema.js
When we do this given a selection and counts,
we can make the tree look better by removing needless parents
New behaviour is to only keep the parents when there is branching under them Example 1:
/map/@34.63293829116424,-81.5339308198741,9z + search for Actinidia the 'issai' cultivar appears in its own checkbox
Example 2:
zoom in on Glasgow and look for Wild garlic, then zoom out eventually it goes under 'Onion' during zooming out (together with Three-cornered leek annotation)
Behaviour about selecting the parent, and parents being duplicated to also just stand for less specific annotations, is as before
The 'Pending Review' nodes still always go under their own node with the same behaviour
Also refactor to use different property names in tree-select ( previous choices reused other …
=> Move construction of types tree later in the flow

src/components/mobile/MobileLayout.js
I'm actually not sure why this works, but:
- I looked at the DOM of the location page http://localhost:3000/locations/1924358/@-0.970248495464574,-90.9548591091169,15z with a non-pannable map
- removed the drawer and noticed the map started to be pannable again
- I did zIndex:2, trying to make it go on top, and it worked
- then zIndex:1 also works, I'm guessing it just has to be defined
Closes #399
=> Add z-index so that the map remains pannable with the location drawer over it

src/App.js, src/components/auth/ConfirmationResendPage.js, src/components/desktop/Header.js, src/components/desktop/SidePane.js
Closes #432 . Now clicking on the map link on desktop will take you to the current view, if in the URL, e.g. from /locations/new to /map will now work. Going to /about and back already worked, I think one of `src/components/connect` components does it.
Original proposal was:
> Restore map view and context of what is happening - e.g. viewing or editing the location.
Don't do the second part, it's confusing to go to a location after clicking on 'Map'.
=> Use current view in /map in top ribbon

src/components/entry/EntryMobile.js, src/components/entry/LightboxMobile.js, src/components/ui/DraggablePane.js
fully open drawer goes over open filter, but partially open drawer goes under open filter. Different resolution than proposed - we don't need to manage the filter being open/closed for the user, it's enough to display them properly.
Closes #450.
=> zIndexes between drawer and filter

src/components/map/MapPage.js, src/utils/throttle.js
Closes #443.
Resetting bounds on resize was an argument to google-map-react, and probably made sense when the view was set through react, but now it's being set to the default view, which kind of ruins the mobile UX. Removed the argument.
Then I added a throttle. The first call happens immediately, but when there are lots of updates - e.g. someone messes around with a scrollbar or clicks really quickly - the calls happen no more frequently than once a second, with intermediate calls dropped.
I tested the throttle by putting logs in, moving the window around like a maniac, and observing that timeouts are cleared much more often than scheduled or delayed calls.
```
wbazant@wbazant-19-01:~/dev/falling-fruit-web$ ag xxx x.log
39:xxxxxxxxxxxxxxx Executing scheduled function throttle2.js:32 …
```
=> Do not reset bounds on resize + throttle map update

src/components/entry/TypesHeader.js
Fixes #462 by always wrapping title title in the same parent container, regardless of whether it also contains a link accordion or not.
For testing:
* http://localhost:3000/locations/1919933
* http://localhost:3000/locations/1734926
=> Always wrap type title in accordion parent

src/components/map/MapPage.js
Closes #423 . Made a follow-up issue to make the cluster click UX dynamic for small counts above one, https://github.com/falling-fruit/falling-fruit-api/issues/30
=> special handleClusterClick when cluster.count === 1

src/components/about/PageTemplate.js, src/components/about/PhotoGridUtils.js, src/components/about/ProjectPage.js
Closes #471. In narrow screens (mobile), the images are now displayed above the text for improved readability.
=> Fix layout issues around images on the About page for narrow screens (#471)

src/components/about/PageTemplate.js, src/components/about/ProjectPage.js
@marceloams Would you check out this version? I got it from Aider with
```
aider --sonnet --no-git src/components/about/PageTemplate.js src/components/about/ProjectPage.js -m "Remove the need for the div-aux hack by using a ::after CSS property or similar"
```
Things seem to display themselves equally well, but I might be missing something.
Closes #471
=> Remove the need for the div-aux element by using a ::after CSS property

src/components/settings/SettingsPage.js
I wanted to see if greying out the icons will make them look better, and then I had the change ready. Have a look at the suggestion! 
I got the grey out from
```
,,aider src/components/settings/SettingsPage.js -m "When GoogleMapTypes doesn't include a mapType and we lower the opacity, also mix in some grey to make the elements look more disabled. Make sure only the images get the grey and not the whole div"
```
Also, I like the attribution in settings - I would propose a bit of whitespace to the UI that the attribution can take up when it appears, instead of the page getting longer after a click.
=> Settings map icons visual improvements

src/components/map/CloseStreetView.js, src/components/map/MapPage.js, src/components/mobile/MobileLayout.js, src/components/ui/TopBar.js
This issue fixes the top padding issue of the Google Street View close button. Sort of just a magic number solution, but it looks correct now.
Closes #498
=> fix: Street View close button location (#498)

src/components/search/Search.js
This PR fixes the issue of having an empty suggestions list pop-up (which is a result of #501) when you focus on the search bar. 
Closes #507
=> fix: unstable height of top bar (#507)

src/components/form/ReviewForm.js
- Aligned behavior with the location access dropdown.
- Prevented the dropdown from triggering the keyboard on mobile.
Closes #499
=> Make Fruiting status dropdown not searchable

src/redux/locationSlice.js
Updated the reducer to correctly handle the `reviews` field, ensuring it retains or updates submitted review instead of defaulting to empty array
Closes #513
=> #513 Fix bug. Review not shown after adding new location with review

src/components/desktop/MainSidePane.js
- Restored standard orange button styling used across the app.
- Maintained the same behavior when the button is disabled.
Closes #511
=> Make 'Add location' button more prominent

src/components/connect/ConnectLocation.js, src/components/connect/ConnectOverscroll.js, src/components/connect/connectRoutes.js
Closes #516. Thanks Ethan for QA, I didn't even know this was a thing.
We set this property:
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y
but only vertically and only in the location drawer.
=> Contain the overscroll for drawer

docs/map-view-redux.md, src/components/map/MapPage.js, src/components/search/Search.js, src/redux/mapSlice.js, src/redux/viewChange.js, src/redux/viewportSlice.js, src/utils/viewportBounds.js
Closes #389 .
Center is in Mercator space, thanks to Ethan for explaining how to get it in https://github.com/falling-fruit/falling-fruit-web/issues/389#issuecomment-2406801451 .
getZoom and getBoundsForScreenSize are AI generated and appear to work. I don't quite understand especially the project/unproject helper functions and their relation to latLngToMercator/mercatorToLatLng .
I could check that the centre works by logging the bounds used, as well as google's getBounds() in  src/redux/mapSlice.js .
To check center, I compared the calculated center to fitBounds + getCenter.
For zoom, I just checked a few examples at a few different scales and it matched - I originally had the zoom wrong and I've dismantled the testing jig that logged values for me. Can't be too far off!
As a bonus I've …
=> Calculate viewport bounds when searching for a place

src/components/form/AddTypeModal.js, src/components/form/TypesSelect.js, src/redux/typeSlice.js
Closes #514 
Thanks Ethan for QAing this thoroughly! I've done something else with redux / callbacks / formik, the previous solution wasn't quite right.
=> Different mechanism for handling new type

src/components/photo/PhotoOrganizer.js, src/components/ui/UploadIcon.js
This improvement replaces the 'Upload Image' text with an upload image icon. By default, the icon is orange, and when dragging files, it changes to a solid black.
Closes  #566
=> feat(uploadImage):  Changed upload text by icon

src/components/form/ReviewForm.js, src/components/form/TypesSelect.js
Closes #553.
Formik can re-validate a field after setFieldValue, but doesn't do that for the whole form, and we have just a global validator (validateLocationStep). Trigger it after adding a new type so the form realises the types field is no longer empty.
=> Validate form after adding a new type

src/components/connect/ConnectNewLocation.js, src/components/form/AddTypeModal.js, src/components/form/LocationForm.js, src/components/form/ReportModal.js, src/components/form/ReviewForm.js, src/components/photo/PhotoUploader.js, src/redux/geolocationSlice.js, src/redux/locationSlice.js, src/redux/mapSlice.js, src/redux/typeSlice.js, src/utils/api.ts
- show errors
- set submitting to false but don't lose form state
Closes #562 
I chose this verbiage for error messages:
```
wbazant@wbazant-19-01:~/dev/falling-fruit-web$ ag 'failed: ' | grep toast
src/components/form/ReportModal.js:33:      toast.error(`Report submission failed: ${e.message}`)
src/components/photo/PhotoUploader.js:39:            toast.error(`Photo upload failed: ${error.message}`)
src/redux/typeSlice.js:60:      toast.error(`Adding new type failed: ${action.error.message}`)
src/redux/locationSlice.js:213:      toast.error(`Location submission failed: ${action.error.message}`)
src/redux/locationSlice.js:225:      toast.error(`Location editing failed: ${action.error.message}`)
src/redux/locationSlice.js:232:      toast.error(`Review submission failed: …
```
=> Better UX when forms fail

src/components/map/ConnectGeolocation.js, src/components/map/GeolocationDot.js, src/components/map/MapPage.js, src/components/map/TrackLocationButton.js, src/components/mobile/LocationPositionNav.js, src/redux/geolocationSlice.js, src/redux/mapSlice.js, src/utils/mapDistance.js
=> When map is panned, geolocation stops centering

scripts/translation_manager.py
Part of #538.
Fyi @mpastoring I've changed our script a bit while writing up instructions for translation issues. If you have ideas for the process or would be up for translating some of the pages, please feel free!
=> Translation manager update

src/components/connect/ConnectInitLocation.js, src/components/connect/ConnectMap.js, src/components/connect/DisconnectInitLocation.js, src/components/connect/connectRoutes.js, src/components/map/MapPage.js, src/components/mobile/LocationNav.js, src/components/mobile/MobileLayout.js, src/components/mobile/Tabs.js, src/components/mobile/TopBarSwitch.js, src/redux/locationSlice.js
Closes #580 
Thanks for spotting! I broke this when changing how the map worked, I've put a bit of code in redux locationSlice, that updated position when the map was moved, but I forgot to only do it on mobile.
I could have added an "only if mobile" to the above but I thought a better solution was to change the routes for adding location: from /locations/new and /locations/new/details, to /locations/init and /locations/new. This works better - the first step of adding location is just a "map but with a marker in the middle" and the second step when the user fills in types, is the correct analogue to the desktop form + map view.
=> Fix add location position

src/components/list/Locations.js
Closes #584 . Thanks @ezwelty for suggesting, I think it helps make the items visually distinct from one another, and it's just the right amount of ornament:
=> Interpunct between type names

src/components/photo/PhotoUploader.js
Closes #556 
https://github.com/user-attachments/assets/4c35cfa1-e9bc-4c4f-878d-bbfdeae2f341
=> On adding photo, scroll into view

src/components/auth/ConfirmationPage.js, src/components/auth/ConfirmationResendPage.js, src/components/auth/LoginPage.js, src/components/auth/PasswordResetPage.js, src/components/auth/PasswordSetPage.js, src/components/auth/SignupPage.js, src/components/form/ReportModal.js, src/components/map/ConnectGeolocation.js, src/redux/authSlice.js, src/redux/geolocationSlice.js, src/utils/api.ts, src/utils/authStore.js
Closes #615 
Closes #614
Closes #613
Closes #599
Closes #565
I tested this a bit with my account. I also tried to make an account with a temp email hwkocmuhkquxswlblp@hthlm.com  from 10minutemail, but the confirmation never arrived.
=> Changes to auth code

src/components/form/LocationForm.js, src/redux/locationSlice.js
Closes #630 
Only took five minutes to fix after I had sleep! this got broken when I was rewriting that code, and forgot that createAsyncThunk output will take args for the wrapped function as a first arg, and dispatch-related args as a second arg.
This is from a console.log put in src/utils/api.ts for editLocation, before and after fix:
=> Fix edit location

package.json, src/components/map/ConnectGeolocation.js, src/redux/geolocationSlice.js
Closes #505 - I didn't test locally on a phone because I'd need to set up https on my laptop, but I propose we try it :).
In terms of how geolocation API is called, I'm replacing https://github.com/streamich/react-use/blob/master/src/useGeolocation.ts 
```
navigator.geolocation.getCurrentPosition(onEvent, onEventError, options);
watchId = navigator.geolocation.watchPosition(onEvent, onEventError, options);
```
with doing just the second call - AI generated and it seems to still work, I'm not sure why the package was doing both of these.
Also, I was able to slightly simplify the existing solution.
=> Try fix geolocation

.github/workflows/main.yml
As announced (https://github.com/actions/cache/discussions/1510), actions/cache@v2 expires on 1 February 2015.
=> Bump actions/cache@v2 to v4

src/components/search/Search.js
Closes #240
I originally added the blur effect only after enter, because it closes the keyboard, but I think it's desirable overall: once the user selected a location, they're done with the search box.
=> Auto-choose on enter, blur on choose

src/components/desktop/Header.js
=> ipad layout for header

package.json, src/components/form/TypesSelect.js, src/components/ui/Select.js, src/components/ui/TypeName.js, src/utils/localizedTypes.ts, src/utils/tokenize.ts, yarn.lock
Closes #635 
Different resolution:
1. show the synonyms when selecting
As Ethan points out, the synonyms can help find the match, but just using them in the background would produce a "matching but not sure why" experience. Meanwhile, they're quite interesting - a bit of trivia about plants of the form: okra is also known as Ladies' fingers - and might help also when browsing.
2. don't reorder search results
I proposed that solution originally, and from searching it seems to be borderline possible, but the library really didn't want me to do it, and it probably has drawbacks. Instead, match from the start only, and use common name + scientific name + all synonyms as possible starts.
=> Improve type search

src/components/entry/EntryOverview.js, src/components/entry/EntryReviews.js, src/components/entry/ReviewSummary.js, src/utils/createReviewSummary.ts
=> Revisit review summary

public/locales/en.json, public/locales/fr.json, scripts/translation_manager.py, src/components/form/formRoutes.js
Closes #672
I was able to also use these:
glossary.list>List
glossary.cancel>Cancel
view_location.date_edited>Updated {{date}}
side_menu.bicycle>Bicycle
A good AI prompt was to make a file with new translations, give it the mobile translations, and ask:
"We have some new translations and want to reuse existing keys. Add a third column to the new translations file, which indicates an existing key or keys that might be a good match, for those that are similar - as well as a forth column with the existing value in english"
I will probably do this again after migrating the locale out of the code.
=> Use mobile translations

src/components/desktop/Header.js, src/components/settings/SettingsPage.js, src/components/ui/Select.js, src/i18n.js
* I placed the select at the right-end of the main menu, so that it is accessed via hamburger menu in tight layout.
* I have no idea why it was necessary to wrap `LanguageSelect` in a styled div rather than style `LanguageSelect` directly.
* The additional element in the header meant increasing the max width of the tight desktop layout.
Closes #683.
=> Move desktop language select to header

src/utils/localizedTypes.ts, src/utils/tokenize.ts
After some experimenting and looking at common names in various languages, I opted to ignore whitespace. There are just so many cases of common synonyms differing by only a space, dash, or lack thereof.
Closes #684.
=> Revise type search in location form

src/utils/buildSelectTree.ts, src/utils/localizedTypes.ts
Closes #730
Should help with #655, although it's not quite a fix - the suggestion there is that if user selects e.g. apples, and moves the map, any apple cultivars that weren't previously visible should still be selected.
=> If on the map is unchecked, all selectable parents should duplicate as their own leaves

src/components/map/MapPage.js, src/redux/mapSlice.js, src/redux/viewportSlice.js
On desktop, we could be coming back to the map component rendering for the first time but the API already loaded - spotted on activity page but maybe also /about will work?
Change the effects in MapPage to install the handler each time the map becomes ready, not just on API load
This then needs a change elsewhere but done
Closes #760
=> Fix how we load map

src/components/form/LocationForm.js, src/utils/form.js
Closes #782 
Thanks Ethan for spotting the bug. I narrowed it down to formik's validation rerunning with initial values - not  formikProps.values - after position changes. The initial value for types is [], so there's an error and submit is greyed out.
It doesn't seem like validateOnMount=true should cause formik to validate after props change and I'm not sure what the purpose of the setting was, but removing it seems to work.
=> Validate after position change not on mount

src/components/ui/Checkbox.js
This PR addresses issue #843 by replacing the border on the checkbox boundary with a box-shadow. The previous border caused click events on the boundary to be missed because it intercepted pointer events. Using box-shadow preserves the visual appearance without blocking clicks.
- Removed `border` property
- Added `box-shadow` with the theme orange color
- Maintained margin and border-radius as before
- Fixes click event issue on checkbox boundaries
- No visual changes expected
- No layout shifts
Fixes #843
=> fix: replace border with box-shadow to avoid click issues (fixes #843)
