falling-fruit/falling-fruit-web

- README.md
:rocket: Ready
Add Lauren's photo + GitHub link (I don't have a LinkedIn lul) to the README 
Fixes #<number>
> 👩🏽‍🌾 Update README with Lauren's photo

- README.md
> 🧸 Add Vasu's photo

- README.md
:rocket: Ready
- added my headshot/linkedin link to `README.md`
N/A
> 📷 Add siraj's link and photo

- README.md
> 👨 Add Arman photo

- README.md
> 🚹 Add archna's photo

- .github/workflows/emojify-pr.yml
Fix emojify-pr action github workflow file
> 👏🏻 Fix emojify action

- .github/workflows/emojify-pr.yml
New release `v1.3.1` resolves all undesired behavior with emojifying a PR.
> 🛀🏼 Greatly improve emojify bot

- src/components/ui/GlobalStyle.js
- src/utils/useBreakpoint.js
Adds constants to theme for easy access when writing media queries. You can use them with `@media ${({ theme }) => theme.device.mobile}` and `@media ${({ theme }) => theme.device.desktop}` when writing styled components.
> 🌝 Add media query constants

- README.md
:rocket: Ready
Updated Siraj's photo src attribute in the `README` to use @Qrtn's well-taken, awesome headshot.
> 🎃 Update siraj's photo

- src/components/entry/EntryDetails.js
- src/components/entry/PhotoGrid.js
- src/components/map/MapPage.js
- src/components/search/Search.js
- src/components/ui/LoadingIndicator.js
- src/components/ui/TopBar.js
:construction: In development
- Added mobile styles for PhotoGrid
- `LoadingIndicator` component 
https://user-images.githubusercontent.com/19193347/111911696-9359cb00-8a34-11eb-9c46-2181d1a836ee.mov
> 🦚 MVP Cleanup 2

- .github/workflows/emojify-pr.yml
Theoretically, this update should fix some body json erros
> 🚴🏽‍♂️ Bump emojify pr

- src/components/mobile/SettingsPage.js
- src/components/ui/Textarea.js
> ✍️ Form textarea

- package.json
- src/components/mobile/SettingsPage.js
- src/components/ui/Slider.js
- yarn.lock
Create a slider that takes in and displays labels and passes back information based on the location of the slider handle.
Fixes #57
> 🦧 Form Slider

- package.json
- src/components/mobile/SettingsPage.js
- src/components/ui/Modal.js
- yarn.lock
This is a modal that shows up when users want to fill out the form. 
Fixes #<number>
> 🧚🏿‍♂️ Form modal

- src/components/entry/EntryDetails.js
- src/utils/locationInfo.js
:rocket: Ready
I made a rookie mistake 😞
> 🤦 Fix seasonality error

- public/index.html
- src/components/desktop/Header.js
- src/components/entry/PhotoGrid.js
- src/components/filter/CheckboxFilters.js
- src/components/filter/Filter.js
- src/components/filter/TreeSelect.js
- src/components/ui/Button.js
- src/components/ui/SettingsAccordion.js
- src/components/ui/TypeTitle.js
:rocket: Ready
- Loads fonts by weight and style over CDN
- Style text with weight names instead of numerical weights
- Fix font weight for scientific name in `TypeTitle.js`
Fixes #85
> 🔧 Safari font fix

- package.json
- src/components/list/EntryList.js
- src/components/list/InfiniteList.js
- src/components/list/PagedList.js
- src/components/map/Map.js
- src/components/map/MapPage.js
- src/contexts/MapContext.js
- src/contexts/SearchContext.js
- yarn.lock
> 🗾 Add list hovering and sync list results on map

- .github/workflows/emojify-pr.yml
Adds blocklist functionality that prevents emojis that aren't recognized by emoji-regex, and other improvements.
> 👩🏽‍🎨 Bump emojify-pr

- README.md
:rocket: Ready
Updated README for Fall 2021 members, no code changes.
https://github.com/hack4impact-uiuc/falling-fruit/blob/bccb7da2c8502c20e232ea4482cb0c887d4c3fb7/README.md
> 🍂 Fall 2021 README

- README.md
:rocket: Ready
Updated readme for Daniel
> 🧞‍♂️ Edit Links for Daniel

- README.md
:rocket: Ready
Change linkedin link for Albert, add picture
> 🤵🏻‍♀️ Change linkedin link for Albert

- README.md
> 🚵🏻 Add Ashank LinkedIn to ReadMe

- src/components/desktop/Header.js
- src/components/entry/Entry.js
- src/components/entry/EntryReviews.js
- src/components/entry/Review.js
- src/components/form/FormikAllSteps.js
- src/components/form/LocationForm.js
- src/components/form/ReviewForm.js
- src/components/form/withLabeledField.js
- src/components/ui/Button.js
- src/components/ui/Select.js
- src/utils/api.ts
Connects the location and review forms to the API.
(Still needs toasts in a future PR to notify the user that the location/review was successfully submitted.)
Fixes #51, fixes #52
- Report forms
- Eventually upload review for new location in the same request, once API is updated to support that
- Add "unverified" checkbox into new location flow
- Convert type selection field in new location form into type tree filter, once filter has finished being built
> 📄 Connect location and review forms

- src/components/filter/CheckboxFilters.js
- src/components/filter/Filter.js
- src/components/filter/FilterButtons.js
- src/components/filter/RCTreeSelect.js
- src/redux/filterSlice.js
- src/utils/buildTypeSchema.js
:construction: In development
* Change select all and deselect all filter buttons styling
* When searching, non-search nodes are styled differently with light grey font color
* Only cultivars are displayed when available
* Pending types are grouped under a "Pending Review" category
> 🔧 Type filtering improvements

- .github/workflows/emojify-pr.yml
- .github/workflows/mappings.json
:rocket: Ready
Fixes #<number>
> Bump emojify-pr-version to v1.5.3

- src/components/list/EntryList.js
- src/components/settings/SettingsPage.js
- src/components/ui/ButtonToggle.js
- src/redux/filterSlice.js
- src/redux/settingsSlice.js
- src/redux/viewChange.js
> 👩🏿‍💼 Metric imperial setting

- src/redux/mapSlice.js
> 🧭 Single Datapoint Cluster Auto-Zoom

- src/components/LoginPage.js
- src/components/desktop/Header.js
- src/components/entry/EntryOverview.js
- src/components/form/LocationForm.js
- src/redux/authSlice.js
- src/redux/filterSlice.js
- src/utils/AuthInitializer.js
- src/utils/api.ts
- src/utils/authStore.js
- src/utils/getInitialUrl.js
> 🔒 Connect auth to API wrapper

- src/components/form/LocationForm.js
- src/components/form/ReportModal.js
- src/components/mobile/MobileLayout.js
- src/components/ui/GlobalStyle.js
- src/components/ui/Toast.js
- src/redux/authSlice.js
- src/utils/api.ts
- yarn.lock
:rocket: Ready
Fixes #53, fixes #106 
- Hooks up reports to API
- If not logged in, requires name, email, and recaptcha
- Toasts with success or error
> 👭🏾 Connect report form

- src/components/entry/EntryWrapper.js
- src/components/list/EntryList.js
- src/components/mobile/ListPage.js
- src/components/mobile/MobileLayout.js
- src/redux/listSlice.js
> 🔧 Fix list view and add photos

- src/redux/mapSlice.js
> 🚀 Selectively clear and add locations

- package.json
- src/components/about/PageTemplate.js
- src/components/entry/Carousel.js
- src/components/entry/Entry.js
- src/components/entry/EntryDrawer.js
- src/components/entry/EntryImagesCard.js
- src/components/entry/EntryReviews.js
- src/components/entry/Lightbox.js
- src/components/entry/Review.js
- src/components/entry/ReviewSummary.js
- src/components/ui/EntryTabs.js
- src/components/ui/GlobalStyle.js
- src/components/ui/Rating.js
- src/constants/ratings.js
- yarn.lock
:rocket: Ready
- Added font smoothing for macOS/iOS to global styles
- Sort and style user's own reviews
- Use stars for reviews and text for fruiting status
- Show summary of reviews
- Remove review title on review tab and add count to tab name
- Tabs are sticky
- Add carousel to replace single image
- PageTemplate fixes (mobile padding)
Fixes #161, #239
> 🎨 Entry & Reviews Polish

- src/components/about/PageTemplate.js
- src/components/settings/SettingsPage.js
:rocket: Ready
- Adds about routes as entries at the bottom of the Settings Page
- Adds information on the current user and the ability to logout (or a call to action to login or signup) at the top of the Settings page on mobile
> 📱 Mobile About and Authentication UI

- src/components/auth/AuthWrappers.js
- src/components/form/FormikWrappers.js
- src/components/form/ReviewForm.js
- src/components/ui/RatingInput.js
:rocket: Ready
- Add star rating input for reviews
- Change `fruiting` to a dropdown field
- Coerce ratings into numbers (from strings) onSubmit
Fixes #161
> 🏛️ Star Rating Slider

- src/components/desktop/NavBack.js
- src/components/desktop/SidePaneSwitch.js
- src/components/entry/EntryOverview.js
- src/components/entry/EntryReviews.js
- src/components/entry/Review.js
- src/components/form/EditableForm.js
- src/components/form/FormikStepper.js
- src/components/form/LocationForm.js
- src/components/form/ReviewForm.js
- src/components/mobile/MobileLayout.js
:rocket: Ready
* Add the ability to edit locations
* Add the ability to edit own reviews
Fixes #149 
* Mobile editing and forms in general
> ✏️ Add desktop location/review editing

- src/components/auth/AccountPage.js
- src/components/auth/LoginPage.js
- src/components/auth/SignupPage.js
- src/components/desktop/Header.js
- src/components/form/FormikWrappers.js
- src/components/settings/SettingsPage.js
:rocket: Ready
* Adds user sign up form
* Uses standard reCAPTCHA
Fixes #249 
* Foraging range fields
* Translated message for duplicate email
> 🖐️ Connect sign up form

- src/components/entry/EntryMobile.js
:rocket: Ready
Resolve bug where the carousel for List Entries had not height
Fixes #<number>
> 🔧 Fix List Entry Carousel

- src/components/entry/EntryReviews.js
- src/components/entry/Review.js
- src/components/entry/ReviewSummary.js
- src/components/ui/ProgressBarStep.js
:rocket: Ready
- Update review styles
- Fixed misaligned progress stepper
> ⬆️ Update review styles, fix progress stepper

- src/components/entry/Review.js
:rocket: Ready
Prevent scrollbar from appearing with from pseudo-element overflow from reviews on desktop
> 🔧 Fix review borders on desktop

- src/components/entry/Entry.js
- src/components/entry/ReviewSummary.js
- src/components/filter/Filter.js
- src/components/filter/RCTreeSelectSkeleton.js
- src/components/form/LocationForm.js
- src/components/map/Map.js
:rocket: Ready
- Fix check for if an entry has photos
- Fix validation step for seasonality
- Fix hidden close button for mobile street view
- Removed '?' icon next to empty review summaries
- Fixed bug where navigating to an entry and back would cause the filter to never load until a map movement
- Fixed bug where filter height would not scale to device height and cut off sidebar elements
> 🐛 Various Bug Fixes

- src/components/entry/Card.js
- src/components/entry/EntryMobile.js
- src/components/form/LocationForm.js
- src/components/ui/CupertinoPane.js
- src/utils/async.ts
https://user-images.githubusercontent.com/19193347/206876237-1942e24d-9556-45bf-a07a-db14a5dfb075.mp4
> 🖐🏿 Click outside closes drawer

- src/components/entry/Review.js
> ⛰️ Show observation date in addition to review date

- src/components/desktop/NavBack.js
- src/components/mobile/MobileLayout.js
> 📱 Don't use stepped forms on mobile and fix edit button not showing on desktop

- src/components/form/FormikWrappers.js
- src/components/form/LocationForm.js
- src/components/map/MapPage.js
> 🚀 Add unverified field to location forms

- src/components/auth/AccountPage.js
- src/components/form/LocationForm.js
- src/components/form/ReportModal.js
- src/components/form/ReviewForm.js
> 🧑🏿‍🏫 Clean up required/optional tags and form validation

- src/components/ui/GlobalStyle.js
Fixed bug where font rendering styles did not get applied to any element
> 🧎🏾 Improve font rendering

- src/components/desktop/SidePaneSwitch.js
- src/components/entry/EntryWrapper.js
Sitewide 404s are sent back to the map and missing entries also show a notification saying the entry was not found. 
Solves #45
> 🥭 Handle 404s

- src/components/entry/ReviewSummary.js
> 🏋🏻 Summarize fruiting status by month

- src/components/form/LocationForm.js
- src/utils/buildTypeSchema.js
Take 2. This time addresses generating the type dropdown in the location form.
> 👩🏻‍🤝‍👩🏽 Handle types without common name

- src/components/entry/Entry.js
- src/components/entry/EntryMobile.js
- src/components/entry/EntryOverview.js
- src/components/map/MapPage.js
- src/components/mobile/MobileLayout.js
- src/components/ui/EntryTabs.js
- src/components/ui/GlobalStyle.js
- Fix position of mobile footer
- Reduce mobile map to visible space between header and footer
- Extend location list view over mobile map footer
- Allow location entry to scroll in list view
- Move EntryTags to inside EntryOverview
Closes #349.
> 🔧 Fix bugs in location view

- README.md
- src/utils/api.ts
Does this when file is missing:
Closes #370
> Throw error when .env is not set up

- src/components/map/Map.js
- src/components/map/MapPage.js
> Add a click handler on the base map and dismiss locations

- src/components/mobile/MobileLayout.js
Keeping the component around but hiding it from display when we navigate away means we don't have to re-initialise it all the time. Closes #390
> Change mobile layout to always include map

- src/components/about/PageTemplate.js
- src/components/mobile/MobileLayout.js
- src/components/settings/SettingsPage.js
> Add bits of padding to mobile layout

- src/components/entry/EntryOverview.js
- src/components/ui/IconBesideText.js
> Tell the svg icons to not shrink and align vertically

- src/components/form/FormLayout.js
- src/components/form/LocationForm.js
- src/components/ui/Modal.js
Closes #451 
I'm actually not sure if recaptcha works reliably after this, and I'm also seeing a 401 from https://fallingfruit.org/api/0.3/user?api_key=AKDJGHSD but I've made a separate issue #456 before I forget this one
> Fix breakage to locationForm

- src/redux/filterSlice.js
- src/redux/mapSlice.js
- src/redux/selectParams.js
> Only provide center for list selectParams

- src/components/connect/ConnectLocation.js
> Avoid refetching location when ConnectLocation goes away briefly

- src/components/entry/EntryOverview.js
Closes #465. Thanks for suggesting this change!
> In handleAddressClick, also partially close the drawer if it is fully open

- src/components/about/AboutDatasetPage.js
- src/components/entry/EntryOverview.js
Closes #479.
A location and an import with line breaks, for testing:
http://localhost:3000/locations/1919691
http://localhost:3000/imports/265
> Render line breaks with white-space: pre-line

- src/components/map/MapPage.js
> Move Google Maps rotation control to bottom left

- src/components/entry/Review.js
> remove "by Anonymous" in anonymous reviews

- src/components/map/PanoramaHandler.js
> Small programmatic jiggle to make the marker appear

- src/components/desktop/Header.js
Added orange outline to Sign In button for improved visual consistency.
Closes #529
> Orange outline for Sign In button

- src/redux/locationSlice.js
Closes #539 
Closes #519
Thanks @ezwelty for catching this, it was a high severity bug!
> Allow changing position when adding location

- src/components/filter/TreeSelectView.js
Also add isDisabled to ScientificName
Closes #473
> skip CommonName if empty otherwise we get an extra margin.

- src/components/auth/AccountPage.js
- src/components/auth/ConfirmationResendPage.js
- src/components/auth/LoginPage.js
- src/components/auth/PasswordResetPage.js
- src/components/auth/PasswordSetPage.js
- src/components/desktop/Header.js
- src/components/mobile/Tabs.js
- src/redux/authSlice.js
- src/utils/appUrl.js
Different symbol depending on whether the user is logged in
Closes #472 
Add a 'fromPage' param to sign in links across the site, then recognise the param and go back after logging in
Closes #343 
Move editProfile to redux
Closes #550
> Log in related fixes

- src/components/auth/AccountPage.js
- src/components/form/LocationForm.js
- src/components/form/ReportModal.js
- src/components/form/ReviewForm.js
> Review 'invalidWhenUntouched' usages

- src/components/photo/PhotoOrganizer.js
Closes #577.
This is how the file drop looks with just color:
https://github.com/user-attachments/assets/947507af-6ea0-4f1a-a5e2-a8193b863f75
> Just orange color when icon lands

- src/components/desktop/Header.js
> feat(#533): Changed gap size between signin  and signup button

- src/utils/appUrl.js
Partially addresses #573 . More of a workaround than a fix but this will make the link to the "add new location" page correct.
> In currentPathWithView, normalize longitude to be within -180,180

- src/components/map/MapPage.js
> Only do the first load after types loaded

- src/components/connect/ConnectLocation.js
Closes #603. Thanks Ethan for spotting the bug!
> Don't get stuck at /list-locations if returning from map to the same location

- src/components/entry/Carousel.js
Removing the rounded from  location drawer photo
Closes #602
Closes #627
> Fix round border from location drawer photo #602

- scripts/translation_manager.py
- src/components/activity/ChangesPeriod.jsx
- src/components/ui/LoadingIndicator.js
> Better translation manager

- public/locales/en.json
- public/locales/fr.json
- src/components/desktop/FilterWrapper.js
- src/components/desktop/MainSidePane.js
- src/components/filter/Filter.js
- src/components/filter/FilterIconButton.js
- src/components/filter/RCTreeSelectSkeleton.js
- src/components/filter/TreeSelectView.js
- src/redux/filterSlice.js
- src/redux/listSlice.js
- src/redux/mapSlice.js
- src/redux/selectParams.js
- src/redux/viewChange.js
Closes #560 
Also, I've used the opportunity to make the paddings / margins in em units, and a bit smaller: the button and types checkbox are a bit less padded, the gaps between the elements are a bit smaller.
> Remove invasive checkbox

- src/components/form/LocationForm.js
- src/components/form/ReviewForm.js
- src/utils/form.js
> Let formik do the default validateOnChange

- src/components/desktop/SidePane.js
- src/components/entry/EntryMobile.js
- src/components/form/formRoutes.js
- src/components/mobile/EditLocationPositionNav.js
- src/components/mobile/MobileLayout.js
Missing commit addressing https://github.com/falling-fruit/falling-fruit-web/pull/658#issuecomment-2614429509 - the push command I executed locally failed and I didn't notice, sorry for merging without this commit!
> Use /locations/:locationId/edit for the form

- src/components/settings/SettingsPage.js
- src/i18n.js
- src/redux/authSlice.js
> Cache language more intentionally

- src/components/about/DataPage.js
- src/components/connect/ConnectSearchParams.js
- src/components/connect/connectRoutes.js
- src/components/table/ShareTheHarvestTable.jsx
- src/utils/useAppHistory.js
> support ?i18n_viz=keys and ?i18n_viz=values

- src/components/filter/Filter.js
- src/redux/filterSlice.js
> Preserve onTheMap and fix types getting reset 

- src/components/mobile/Tabs.js
- src/utils/useAppHistory.js
> Don't append view to a withFromPage url

- src/redux/locationSlice.js
> After init new location, or on clear, correctly set isBeingInitializedMobile to false

- src/components/mobile/MobileLayout.js
> Don't show tablist when editing location

- public/locales/en.json
- src/components/list/DistanceText.js
- src/constants/list.js
Closes #531
Wasn't just one AI query, took about five, but still quite straightforward!
Checked meters / miles work in English. Let's wait with translation into French until the English locale is finished.
> Internationalize the constants

- src/components/form/ReviewForm.js
> Show 'Leave a review' on desktop only

- src/components/auth/authRoutes.js
- src/components/mobile/MobileLayout.js
> Don't show tab lists for /users/:id

- src/components/desktop/SettingsButton.js
- src/components/desktop/SidePane.js
- src/components/form/LocationForm.js
- src/components/form/ReviewForm.js
- src/components/form/formRoutes.js
- src/redux/locationSlice.js
- src/redux/reviewSlice.js
> Save intermediate state of AddLocation, EditLocation, and EditReview forms

- src/components/desktop/SettingsButton.js
> min-height for settings button so it doesn't shrink

- src/components/activity/ChangesPeriod.jsx
- src/components/auth/ConfirmationPage.js
- src/components/auth/ConfirmationResendPage.js
- src/components/auth/LoginPage.js
- src/components/auth/PasswordResetPage.js
- src/components/auth/PasswordSetPage.js
- src/components/auth/SignInLink.js
- src/components/auth/SignupPage.js
- src/components/auth/authRoutes.js
- src/components/auth/path.js
- src/components/auth/withAuthRedirect.js
- src/components/connect/ConnectMap.js
- src/components/desktop/DesktopLayout.js
- src/components/desktop/Header.js
- src/components/entry/EntryOverview.js
- src/components/entry/Review.js
- src/components/mobile/MobileLayout.js
- src/components/mobile/Tabs.js
- src/components/profile/profileRoutes.js
- src/utils/appUrl.js
- src/utils/useAppHistory.js
> Refactor + fix about logged in user being redirected

- docs/setup.md
In response to a setup question about current docs, should be clearer!
> Clarify param in the doc

- src/components/form/FormikWrappers.js
- src/components/map/MapPage.js
Closes #600
I could reproduce the problem with labels shifted upwards but no quick AI fix worked and I only have the iphone access for a bit, so submitting the other two fixes.
> Fix some iphone quirks

- src/i18n.js
> Correct the menu option

- src/components/filter/Filter.js
- src/components/filter/FilterButtons.js
Don't offer a press when pressing would have no effect
Closes #728
> Select all / Deselect all buttons can be disabled

- src/utils/form.js
Update condition to handle undefined values instead of checking for null
solves [744](https://github.com/falling-fruit/falling-fruit-web/issues/744)
> Fix observe state when selection 'Flowers'

- src/App.js
- src/components/about/AboutDatasetPage.js
- src/components/about/DataPage.js
- src/components/about/InThePressPage.js
- src/components/about/ProjectPage.js
- src/components/about/ShareTheHarvestPage.js
- src/components/activity/ActivityPage.js
- src/components/auth/AccountPage.js
- src/components/auth/ConfirmationResendPage.js
- src/components/auth/LoginPage.js
- src/components/auth/PasswordResetPage.js
- src/components/auth/PasswordSetPage.js
- src/components/auth/SignupPage.js
- src/components/profile/UserProfile.js
- src/components/settings/SettingsPage.js
- src/components/ui/PageTemplate.js
- src/i18n.js
> Add logo over auth pages and redirect logged out users to /users/sign_in

- src/i18n.js
> Make i18next use lowercase language codes

- public/locales/ar.json
- public/locales/de.json
- public/locales/el.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/he.json
- public/locales/it.json
- public/locales/nl.json
- public/locales/pl.json
- public/locales/pt.json
- public/locales/sv.json
- public/locales/tr.json
- public/locales/uk.json
- public/locales/vi.json
- public/locales/zh-hans.json
- public/locales/zh-hant.json
- src/utils/localizedTypes.ts
> Localize Pending Review

- src/components/entry/Review.js
- src/components/entry/textFormatters.js
Closes #755 
Thanks for spotting @ezwelty !
> Add missing language param

- public/locales/en.json
- public/locales/it.json
- public/locales/pl.json
- public/locales/zh-hant.json
- src/redux/authSlice.js
- src/utils/AuthInitializer.js
> If refresh token is present but invalid, redirect to sign in

- public/locales/pl.json
- src/components/map/TypeLabels.js
- src/utils/buildSelectTree.ts
- src/utils/localizedTypes.ts
> Better labels for cultivars

- src/components/form/withLabeledField.js
- src/components/ui/Toast.js
> Remove side margins from toast

- public/locales/en.json
- src/components/form/AddTypeModal.js
Closes #520 
I added a type called 'test', refreshed page, searched for 'test' in type menu, and observed that it is selected in the default selection.
> Hardcode default categories

- src/App.js
- src/components/entry/EntryOverview.js
- src/components/entry/Review.js
- src/components/entry/ReviewStats.js
- src/components/entry/ReviewSummary.js
- src/components/entry/overview/TypesHeader.js
- src/components/form/LocationForm.js
- src/components/ui/TypeName.js
Closes #776 
I think this works? Tested by opening map in ltr and observing a toast - e.g. http://localhost:3000/locations/1773702/success , going to settings, changing to a rtl language, and seeing a toast the other way.
> Add toast RTL

- src/components/desktop/Header.js
> Header over close street view

- src/components/form/TypesSelect.js
- src/components/ui/Select.js
> Allow typing 'raspberry' twice

- src/components/connect/ConnectReview.js
- src/components/connect/connectRoutes.js
- src/components/entry/EntryReviews.js
- src/components/entry/Review.js
- src/components/form/ReviewForm.js
- src/redux/reviewSlice.js
Closes #732 
Closes #654
Closes #794
Edit: I also made  #791 when working on this but either lost the commit or didn't actually do it!
> Changes to edit review UI

- src/components/connect/ConnectTopPanel.js
- src/components/connect/connectRoutes.js
> Limit the context of the top panel

- src/components/form/TypesSelect.js
- src/components/ui/Select.js
> Move the CSS from the global styling to individual component

- src/components/ui/AddLocation.js
> Fix add location - mobile should go to /locations/init

- src/components/activity/ActivityDiary.ts
- src/components/activity/DiaryEntry.js
- src/components/activity/RecentChangesPage.js
- src/redux/activitySlice.js
> Fix activity page regressions

- src/components/map/MapPage.js
Closes #837
FYI @ezwelty, I'll merge this so anyone cloning the branch has a working setup, no idea what the actual solution for broad compatibility would be. Maybe switching away from Google Maps to OSM .
> Google maps setup

- src/components/form/LocationForm.js
> Pass an id to the unverified checkbox

- src/components/map/MapPage.js
> Explicitly switch position of native controls

- src/redux/authSlice.js
- src/redux/viewportSlice.js
- src/utils/authStore.js
> Remember last map view
